app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/gymtime
    username: postgres
    password: password

spring:
  profiles:
    active: '@spring.profiles.active@'

application:
  jwt:
    secretKey: testsecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 30
  password:
    specialChar: true
    capitalLetter: true
    number: true
    min: 8
    max: 30